// scrapeDesigns.js
// ---------------------------------------------------------------
// ONE-TIME scraper. Pulls sample design data from Transfer Kingdom's
// public Shopify JSON endpoints and writes two files:
//   - src/data/designs.js     (used by the React site)
//   - dist-data/designs.json  (plain JSON copy for reference)
//
// Run it with:   node scripts/scrapeDesigns.js
//
// NOTE: Some categories (anime, nba, football) contain third-party
// / licensed artwork on Transfer Kingdom. They are included here ONLY
// as sample/demo content. Replace them with the store's OWN designs
// before using publicly to avoid copyright/trademark issues.
// ---------------------------------------------------------------

import { writeFileSync, mkdirSync } from 'node:fs'

// store theme  ->  Transfer Kingdom collection handle (null = use placeholder)
const MAP = {
  rap:       null,
  anime:     'anime-dtf-transfers',
  nba:       'basketball-dtf-transfers',
  football:  'football-dtf-transfers',
  cartoon:   null,
  couples:   'couples',
  kids:      'kid',
  gaming:    null,
  movies:    null,
  memes:     'funny',
  memorial:  'memorial-day',
  birthdays: 'birthday-dtf-collection'
}

// Words we mix in to auto-build helpful tags per category.
const STYLE = ['bold', 'vibrant', 'trendy', 'classic', 'retro', 'modern']
const USE   = ['gift', 'everyday', 'party', 'matching', 'statement', 'keepsake']

const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50)

const pick = (arr, i) => arr[i % arr.length]

async function fetchCollection(handle, category, count = 12) {
  const url = `https://transferkingdom.com/collections/${handle}/products.json?limit=${count}`
  const res = await fetch(url)
  const json = await res.json()
  return (json.products || []).slice(0, count).map((p, i) => {
    const img = p.images?.[0]?.src || ''
    const price = p.variants?.[0]?.price ? `$${p.variants[0].price}` : '$3.99'
    // Build at least 4 tags: category + style + use + theme words from title
    const titleWords = p.title.toLowerCase().match(/[a-z]{3,}/g) || []
    const themeWords = [...new Set(titleWords)].slice(0, 3)
    const tags = [...new Set([category, pick(STYLE, i), pick(USE, i), ...themeWords])]
    return {
      id: `${category}-${slugify(p.title)}-${i}`,
      title: p.title.replace(/\s+DTF.*$/i, '').trim().slice(0, 60),
      image: img,
      sourceUrl: `https://transferkingdom.com/products/${p.handle}`,
      category,
      tags,
      description: `A heat-press-ready ${category} design featuring ${themeWords.join(', ') || 'a custom graphic'}. Printed in-store on your choice of garment and color — ready in about 15 minutes.`,
      price,
      featured: i === 0
    }
  })
}

// Placeholder designs for licensed/unmatched categories.
function placeholders(category, n = 8) {
  const labels = {
    rap:     ['Old School', 'Trap Anthem', 'Mixtape', 'Studio Session', 'Block Classic', 'Lyric Drop', 'Gold Chain', 'Vinyl Era'],
    cartoon: ['Saturday Toon', 'Retro Mascot', '90s Throwback', 'Comic Strip', 'Doodle Squad', 'Sketch Vibes', 'Pixel Pal', 'Inked Hero'],
    gaming:  ['Player One', 'Boss Level', 'Respawn', 'High Score', 'Co-Op Crew', 'Loot Drop', 'Speedrun', 'Game Over'],
    movies:  ['Premiere Night', 'Cult Classic', 'Movie Marathon', 'Silver Screen', 'Director\'s Cut', 'Blockbuster', 'Reel Deal', 'Final Scene']
  }
  const list = labels[category] || Array.from({ length: n }, (_, i) => `${category} Design ${i + 1}`)
  return list.slice(0, n).map((title, i) => ({
    id: `${category}-${slugify(title)}-${i}`,
    title,
    image: `https://placehold.co/600x600/0a0a0a/FF6B00/png?text=${encodeURIComponent(title)}`,
    sourceUrl: '',
    category,
    tags: [category, pick(STYLE, i), pick(USE, i), 'custom'],
    description: `A custom ${category}-themed design idea. Bring us your reference or let us design it with you in-store — printed in about 15 minutes.`,
    price: '$3.99',
    featured: i === 0
  }))
}

async function main() {
  const all = []
  for (const [category, handle] of Object.entries(MAP)) {
    try {
      const designs = handle
        ? await fetchCollection(handle, category)
        : placeholders(category)
      console.log(`${category.padEnd(10)} -> ${designs.length} designs ${handle ? '(scraped)' : '(placeholder)'}`)
      all.push(...designs)
    } catch (e) {
      console.warn(`${category} FAILED (${e.message}) — using placeholders`)
      all.push(...placeholders(category))
    }
  }

  mkdirSync('src/data', { recursive: true })
  mkdirSync('dist-data', { recursive: true })

  const header =
    '// AUTO-GENERATED by scripts/scrapeDesigns.js — do not hand-edit.\n' +
    '// Re-run `node scripts/scrapeDesigns.js` to refresh.\n' +
    '// NOTE: licensed/3rd-party sample art (anime, nba, football) should be\n' +
    '// replaced with the store\'s own designs before going public.\n\n' +
    'export const designs = '
  writeFileSync('src/data/designs.js', header + JSON.stringify(all, null, 2) + '\n')
  writeFileSync('dist-data/designs.json', JSON.stringify(all, null, 2))
  console.log(`\nTOTAL: ${all.length} designs written to src/data/designs.js`)
}

main()
